title: Cuma Cerita
description: Vini Vidi Vici

url: "http://cumacerita.github.io"
gambar: "http://aozoraworld.files.wordpress.com/2013/05/oreki-x-chitanda.jpg"
twitter_username: mzaini30

lokasi: "/home/cuma cerita (git)"
permalink: "/:year/:month/:day/:title.html"

gems:
  - jekyll-paginate

paginate: 12
paginate_path: "/halaman/:num/"